server:
  port: 2020
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    river-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:26257/test?sslmode=disable
    #    url: jdbc:postgresql://localhost:5432/test1?sslmode=disable
    username: root
    password:
  #  flyway:
  #    baseline-on-migrate: true
  cloud:
    sentinel:
      filter:
        enabled: false
      transport:
        port: 8719
        dashboard: localhost:8080
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
test:
  test: hello world!